# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 756)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #22222e;\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_capture = QtWidgets.QPushButton(self.centralwidget)
        self.input_capture.setGeometry(QtCore.QRect(20, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.input_capture.setFont(font)
        self.input_capture.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.input_capture.setObjectName("input_capture")
        self.process_discovery = QtWidgets.QPushButton(self.centralwidget)
        self.process_discovery.setGeometry(QtCore.QRect(20, 70, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.process_discovery.setFont(font)
        self.process_discovery.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.process_discovery.setObjectName("process_discovery")
        self.command_line_interface = QtWidgets.QPushButton(self.centralwidget)
        self.command_line_interface.setGeometry(QtCore.QRect(20, 130, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.command_line_interface.setFont(font)
        self.command_line_interface.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.command_line_interface.setObjectName("command_line_interface")
        self.system_info_discovery = QtWidgets.QPushButton(self.centralwidget)
        self.system_info_discovery.setGeometry(QtCore.QRect(20, 190, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.system_info_discovery.setFont(font)
        self.system_info_discovery.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.system_info_discovery.setObjectName("system_info_discovery")
        self.file_and_directory_discovery = QtWidgets.QPushButton(self.centralwidget)
        self.file_and_directory_discovery.setGeometry(QtCore.QRect(20, 250, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.file_and_directory_discovery.setFont(font)
        self.file_and_directory_discovery.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.file_and_directory_discovery.setObjectName("file_and_directory_discovery")
        self.remote_file_copy = QtWidgets.QPushButton(self.centralwidget)
        self.remote_file_copy.setGeometry(QtCore.QRect(20, 307, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.remote_file_copy.setFont(font)
        self.remote_file_copy.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.remote_file_copy.setObjectName("remote_file_copy")
        self.file_deletion = QtWidgets.QPushButton(self.centralwidget)
        self.file_deletion.setGeometry(QtCore.QRect(20, 370, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.file_deletion.setFont(font)
        self.file_deletion.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.file_deletion.setObjectName("file_deletion")
        self.screen_capture = QtWidgets.QPushButton(self.centralwidget)
        self.screen_capture.setGeometry(QtCore.QRect(20, 430, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.screen_capture.setFont(font)
        self.screen_capture.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.screen_capture.setObjectName("screen_capture")
        self.clipboard_data = QtWidgets.QPushButton(self.centralwidget)
        self.clipboard_data.setGeometry(QtCore.QRect(20, 490, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.clipboard_data.setFont(font)
        self.clipboard_data.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.clipboard_data.setObjectName("clipboard_data")
        self.audio_capture = QtWidgets.QPushButton(self.centralwidget)
        self.audio_capture.setGeometry(QtCore.QRect(20, 550, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.audio_capture.setFont(font)
        self.audio_capture.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.audio_capture.setObjectName("audio_capture")
        self.video_capture = QtWidgets.QPushButton(self.centralwidget)
        self.video_capture.setGeometry(QtCore.QRect(20, 610, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.video_capture.setFont(font)
        self.video_capture.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.video_capture.setObjectName("video_capture")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(260, 10, 801, 681))
        self.textBrowser.setStyleSheet("background-color: #BABAC1;\n"
"color: black;\n"
"")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setObjectName("textBrowser")
        self.remove_client = QtWidgets.QPushButton(self.centralwidget)
        self.remove_client.setGeometry(QtCore.QRect(20, 670, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.remove_client.setFont(font)
        self.remove_client.setStyleSheet("QPushButton\n"
"{\n"
"    color:#BABABA;\n"
"    background-color: #2F2F3D;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #40404D; \n"
"    color: #000000;\n"
"     border: 2px solid black;\n"
"}\n"
"")
        self.remove_client.setObjectName("remove_client")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_capture.setText(_translate("MainWindow", "Input Capture"))
        self.process_discovery.setText(_translate("MainWindow", "Process Discovery"))
        self.command_line_interface.setText(_translate("MainWindow", "Command-Line Interface"))
        self.system_info_discovery.setText(_translate("MainWindow", "System Information Discovery"))
        self.file_and_directory_discovery.setText(_translate("MainWindow", "File and Directory Discovery"))
        self.remote_file_copy.setText(_translate("MainWindow", "Remote File Copy"))
        self.file_deletion.setText(_translate("MainWindow", "File Deletion"))
        self.screen_capture.setText(_translate("MainWindow", "Screen Capture"))
        self.clipboard_data.setText(_translate("MainWindow", "Clipboard Data"))
        self.audio_capture.setText(_translate("MainWindow", " Audio Capture"))
        self.video_capture.setText(_translate("MainWindow", "Video Capture"))
        self.remove_client.setText(_translate("MainWindow", "Remove client"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
